#! /bin/sh

pgrep -x sxhkd >/dev/null || sxhkd &

xrandr --output eDP-1 --mode 1920x1200 --primary

bspc monitor eDP-1 -d 1 2 3 4 5

bspc config focus_follows_pointer true
bspc config focused_border_color "#7899FA"
bspc config normal_border_color "#1f222b"
bspc config border_width 2
bspc config borderless_monocle true

bspc config active_border_color "#bd93f9"
bspc config presel_feedback_color "#6272a4"

xsetroot -cursor_name left_ptr

bspc config single_monocle true
bspc config gapless_monocle false
bspc config split_ratio 0.51
bspc config window_gap 2

bspc config pointer_follows_monitor true
bspc config pointer_motion_interval 7
bspc config pointer_follows_focus true
bspc config pointer_modifier mod4
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action3 resize_corner

bspc config automatic_scheme longest_side
bspc config initial_polarity second_child
bspc config removal_adjustment true

bspc rule -a feh state=floating
bspc rule -a steam center=on
bspc rule -a steam desktop='^5'

xinput set-prop "CX Wireless mouse -1k dongle Mouse" "libinput Accel Profile Enabled" 0, 1
xinput set-prop "CX Wireless mouse -1k dongle Mouse" "libinput Accel Speed" 0

feh --bg-fill /home/kyd0/Wallpaper/wallpaper1.jpg

polybar mybar &
picom &
